spring.application.name=Codigo Gourmet
server.port=8080

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/bd_factura?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
