spring.application.name=Codigo Gourmet
server.port=8080

spring.datasource.url=jdbc:h2:mem:codigo_gourmet
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true